modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "ycdm"
version = "${version}"
displayName = "Potion Abilities"
authors = "To_Craft"
description = '''
You can do Magic!
'''
#logoFile = ""

[[dependencies.ycdm]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ycdm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ycdm]]
modId = "craftedcore"
mandatory = true
versionRange = "[1.1,)"
ordering = "AFTER"
side = "BOTH"